name: sweep_dreams
description: A Flutter app for checking street sweeping schedules in San Francisco
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  http: ^1.1.2
  
  # Location services
  geolocator: ^14.0.2
  
  # State management
  provider: ^6.1.1
  
  # Date/time formatting
  intl: ^0.20.2
  
  # Icons
  cupertino_icons: ^1.0.6

  # FCM
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: "../docs/favicon.png"
  
  # iOS
  ios: true
  remove_alpha_ios: true
  
  # Web
  web:
    generate: true
    image_path: "../docs/favicon.png"
    background_color: "#ffffff"
    theme_color: "#5B4CDB"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

