name: sweep_dreams
description: A beautiful Flutter app for checking street sweeping schedules in San Francisco
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  http: ^1.1.2
  
  # Location services
  geolocator: ^14.0.2
  
  # State management
  provider: ^6.1.1
  
  # Date/time formatting
  intl: ^0.20.2
  
  # Icons
  cupertino_icons: ^1.0.6

  # FCM
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

