name: sweep_dreams
description: A Flutter app for checking street sweeping schedules in San Francisco
publish_to: 'none'
version: 0.8.3+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  http: ^1.1.2
  
  # Location services
  geolocator: ^14.0.2
  
  # State management
  provider: ^6.1.1
  
  # Date/time formatting
  intl: ^0.20.2
  
  # Icons
  cupertino_icons: ^1.0.6

  # FCM
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_svg: ^2.2.3
  mapbox_maps_flutter: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: "assets/icon.png"

  # iOS
  ios: true
  remove_alpha_ios: true

  # Android
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  android_generate_adaptive_icon: true
  adaptive_icon_margin_percentage: 0

  # Web
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#0d1b2a"
    theme_color: "#0d1b2a"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

